"""add user trade tracking

Revision ID: ec1ca7a4a3ae
Revises: 
Create Date: 2026-05-17 14:04:50.363207

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers
revision = 'ec1ca7a4a3ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_code', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('license_quota', sa.Integer(), nullable=False),
    sa.Column('license_used', sa.Integer(), nullable=False),
    sa.Column('license_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_admin_code'), 'admins', ['admin_code'], unique=True)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('ai_market_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('signal', sa.String(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('analysis', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_market_states_id'), 'ai_market_states', ['id'], unique=False)
    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_lot', sa.Boolean(), nullable=True),
    sa.Column('fixed_lot', sa.Float(), nullable=True),
    sa.Column('risk_percent', sa.Float(), nullable=True),
    sa.Column('max_trades', sa.Integer(), nullable=True),
    sa.Column('aggressive_mode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_settings_id'), 'ai_settings', ['id'], unique=False)
    op.create_table('ai_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_executed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_signals_id'), 'ai_signals', ['id'], unique=False)
    op.create_table('ai_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('trial_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_plan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_users_email'), 'ai_users', ['email'], unique=True)
    op.create_index(op.f('ix_ai_users_id'), 'ai_users', ['id'], unique=False)
    op.create_table('live_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(), nullable=True),
    sa.Column('mt5_login', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('trade_type', sa.String(), nullable=False),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('mt5_ticket', sa.String(), nullable=True),
    sa.Column('ai_signal_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_ai_trade', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_trades_id'), 'live_trades', ['id'], unique=False)
    op.create_table('ticket_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('master_ticket', sa.String(), nullable=False),
    sa.Column('client_ticket', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_by_client', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_maps_client_ticket'), 'ticket_maps', ['client_ticket'], unique=False)
    op.create_index(op.f('ix_ticket_maps_execution_id'), 'ticket_maps', ['execution_id'], unique=False)
    op.create_index(op.f('ix_ticket_maps_id'), 'ticket_maps', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_maps_license_id'), 'ticket_maps', ['license_id'], unique=False)
    op.create_index(op.f('ix_ticket_maps_master_ticket'), 'ticket_maps', ['master_ticket'], unique=False)
    op.create_index(op.f('ix_ticket_maps_symbol'), 'ticket_maps', ['symbol'], unique=False)
    op.create_table('admin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('support_email', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_profiles_admin_id'), 'admin_profiles', ['admin_id'], unique=True)
    op.create_index(op.f('ix_admin_profiles_id'), 'admin_profiles', ['id'], unique=False)
    op.create_table('expert_advisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code_name', sa.String(), nullable=False),
    sa.Column('ea_code', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mode_type', sa.String(), nullable=False),
    sa.Column('is_shareable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_advisors_admin_id'), 'expert_advisors', ['admin_id'], unique=False)
    op.create_index(op.f('ix_expert_advisors_code_name'), 'expert_advisors', ['code_name'], unique=False)
    op.create_index(op.f('ix_expert_advisors_ea_code'), 'expert_advisors', ['ea_code'], unique=True)
    op.create_index(op.f('ix_expert_advisors_id'), 'expert_advisors', ['id'], unique=False)
    op.create_table('license_quota_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('requested_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_quota_requests_id'), 'license_quota_requests', ['id'], unique=False)
    op.create_table('admin_ea_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_admin_id', sa.Integer(), nullable=False),
    sa.Column('target_admin_id', sa.Integer(), nullable=False),
    sa.Column('source_ea_id', sa.Integer(), nullable=False),
    sa.Column('source_ea_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['source_ea_id'], ['expert_advisors.id'], ),
    sa.ForeignKeyConstraint(['target_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_ea_links_id'), 'admin_ea_links', ['id'], unique=False)
    op.create_index(op.f('ix_admin_ea_links_source_admin_id'), 'admin_ea_links', ['source_admin_id'], unique=False)
    op.create_index(op.f('ix_admin_ea_links_source_ea_code'), 'admin_ea_links', ['source_ea_code'], unique=False)
    op.create_index(op.f('ix_admin_ea_links_source_ea_id'), 'admin_ea_links', ['source_ea_id'], unique=False)
    op.create_index(op.f('ix_admin_ea_links_target_admin_id'), 'admin_ea_links', ['target_admin_id'], unique=False)
    op.create_table('copier_trade_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_admin_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('ea_code', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('master_ticket', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('lot_size', sa.String(), nullable=True),
    sa.Column('sl', sa.String(), nullable=True),
    sa.Column('tp', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.ForeignKeyConstraint(['source_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copier_trade_events_ea_code'), 'copier_trade_events', ['ea_code'], unique=False)
    op.create_index(op.f('ix_copier_trade_events_ea_id'), 'copier_trade_events', ['ea_id'], unique=False)
    op.create_index(op.f('ix_copier_trade_events_id'), 'copier_trade_events', ['id'], unique=False)
    op.create_index(op.f('ix_copier_trade_events_master_ticket'), 'copier_trade_events', ['master_ticket'], unique=False)
    op.create_index(op.f('ix_copier_trade_events_source_admin_id'), 'copier_trade_events', ['source_admin_id'], unique=False)
    op.create_index(op.f('ix_copier_trade_events_symbol'), 'copier_trade_events', ['symbol'], unique=False)
    op.create_table('ea_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ea_symbols_ea_id'), 'ea_symbols', ['ea_id'], unique=False)
    op.create_index(op.f('ix_ea_symbols_id'), 'ea_symbols', ['id'], unique=False)
    op.create_index(op.f('ix_ea_symbols_symbol_name'), 'ea_symbols', ['symbol_name'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('mode_type', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_device_id', sa.String(), nullable=True),
    sa.Column('activated_device_name', sa.String(), nullable=True),
    sa.Column('first_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branding_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('execution_enabled', sa.Boolean(), nullable=False),
    sa.Column('execution_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('mt5_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_trade_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_activated_device_id'), 'licenses', ['activated_device_id'], unique=False)
    op.create_index(op.f('ix_licenses_admin_id'), 'licenses', ['admin_id'], unique=False)
    op.create_index(op.f('ix_licenses_client_email'), 'licenses', ['client_email'], unique=False)
    op.create_index(op.f('ix_licenses_ea_id'), 'licenses', ['ea_id'], unique=False)
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True)
    op.create_table('master_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('mt_login', sa.String(), nullable=False),
    sa.Column('mt_password', sa.String(), nullable=False),
    sa.Column('mt_server', sa.String(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_accounts_ea_id'), 'master_accounts', ['ea_id'], unique=False)
    op.create_index(op.f('ix_master_accounts_id'), 'master_accounts', ['id'], unique=False)
    op.create_table('robot_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('lot_size', sa.String(), nullable=True),
    sa.Column('sl', sa.String(), nullable=True),
    sa.Column('tp', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_trades_admin_id'), 'robot_trades', ['admin_id'], unique=False)
    op.create_index(op.f('ix_robot_trades_ea_id'), 'robot_trades', ['ea_id'], unique=False)
    op.create_index(op.f('ix_robot_trades_id'), 'robot_trades', ['id'], unique=False)
    op.create_index(op.f('ix_robot_trades_symbol'), 'robot_trades', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('sl', sa.String(), nullable=True),
    sa.Column('tp', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_admin_id'), 'signals', ['admin_id'], unique=False)
    op.create_index(op.f('ix_signals_ea_id'), 'signals', ['ea_id'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('client_activations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_activations_id'), 'client_activations', ['id'], unique=False)
    op.create_index(op.f('ix_client_activations_license_id'), 'client_activations', ['license_id'], unique=True)
    op.create_table('client_mt5_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('server', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('metaapi_account_id', sa.String(), nullable=True),
    sa.Column('metaapi_state', sa.String(), nullable=True),
    sa.Column('metaapi_connection_status', sa.String(), nullable=True),
    sa.Column('metaapi_region', sa.String(), nullable=True),
    sa.Column('metaapi_type', sa.String(), nullable=True),
    sa.Column('metaapi_reliability', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_error', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_auto_trade', sa.Boolean(), nullable=True),
    sa.Column('ai_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_ai_trades', sa.Integer(), nullable=True),
    sa.Column('risk_percent', sa.Float(), nullable=True),
    sa.Column('allow_buy', sa.Boolean(), nullable=True),
    sa.Column('allow_sell', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('metaapi_account_id')
    )
    op.create_index(op.f('ix_client_mt5_accounts_id'), 'client_mt5_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_client_mt5_accounts_license_id'), 'client_mt5_accounts', ['license_id'], unique=True)
    op.create_table('client_symbol_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=False),
    sa.Column('trade_direction', sa.String(), nullable=False),
    sa.Column('trades_per_signal', sa.Integer(), nullable=False),
    sa.Column('lot_size', sa.String(), nullable=False),
    sa.Column('max_open_trades', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_symbol_settings_id'), 'client_symbol_settings', ['id'], unique=False)
    op.create_index(op.f('ix_client_symbol_settings_license_id'), 'client_symbol_settings', ['license_id'], unique=False)
    op.create_index(op.f('ix_client_symbol_settings_symbol_name'), 'client_symbol_settings', ['symbol_name'], unique=False)
    op.create_table('mt5_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_name', sa.String(), nullable=False),
    sa.Column('worker_type', sa.String(), nullable=False),
    sa.Column('terminal_path', sa.String(), nullable=False),
    sa.Column('data_path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_busy', sa.Boolean(), nullable=False),
    sa.Column('current_license_id', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mt5_workers_current_license_id'), 'mt5_workers', ['current_license_id'], unique=False)
    op.create_index(op.f('ix_mt5_workers_id'), 'mt5_workers', ['id'], unique=False)
    op.create_index(op.f('ix_mt5_workers_worker_name'), 'mt5_workers', ['worker_name'], unique=True)
    op.create_table('trade_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copier_event_id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('master_ticket', sa.String(), nullable=False),
    sa.Column('client_ticket', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('lot_size', sa.String(), nullable=True),
    sa.Column('sl', sa.String(), nullable=True),
    sa.Column('tp', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['copier_event_id'], ['copier_trade_events.id'], ),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_executions_client_ticket'), 'trade_executions', ['client_ticket'], unique=False)
    op.create_index(op.f('ix_trade_executions_copier_event_id'), 'trade_executions', ['copier_event_id'], unique=False)
    op.create_index(op.f('ix_trade_executions_ea_id'), 'trade_executions', ['ea_id'], unique=False)
    op.create_index(op.f('ix_trade_executions_id'), 'trade_executions', ['id'], unique=False)
    op.create_index(op.f('ix_trade_executions_license_id'), 'trade_executions', ['license_id'], unique=False)
    op.create_index(op.f('ix_trade_executions_master_ticket'), 'trade_executions', ['master_ticket'], unique=False)
    op.create_index(op.f('ix_trade_executions_symbol'), 'trade_executions', ['symbol'], unique=False)
    op.create_table('mt5_verification_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('client_mt5_account_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('worker_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_mt5_account_id'], ['client_mt5_accounts.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['mt5_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mt5_verification_jobs_id'), 'mt5_verification_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mt5_verification_jobs_id'), table_name='mt5_verification_jobs')
    op.drop_table('mt5_verification_jobs')
    op.drop_index(op.f('ix_trade_executions_symbol'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_master_ticket'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_license_id'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_id'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_ea_id'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_copier_event_id'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_client_ticket'), table_name='trade_executions')
    op.drop_table('trade_executions')
    op.drop_index(op.f('ix_mt5_workers_worker_name'), table_name='mt5_workers')
    op.drop_index(op.f('ix_mt5_workers_id'), table_name='mt5_workers')
    op.drop_index(op.f('ix_mt5_workers_current_license_id'), table_name='mt5_workers')
    op.drop_table('mt5_workers')
    op.drop_index(op.f('ix_client_symbol_settings_symbol_name'), table_name='client_symbol_settings')
    op.drop_index(op.f('ix_client_symbol_settings_license_id'), table_name='client_symbol_settings')
    op.drop_index(op.f('ix_client_symbol_settings_id'), table_name='client_symbol_settings')
    op.drop_table('client_symbol_settings')
    op.drop_index(op.f('ix_client_mt5_accounts_license_id'), table_name='client_mt5_accounts')
    op.drop_index(op.f('ix_client_mt5_accounts_id'), table_name='client_mt5_accounts')
    op.drop_table('client_mt5_accounts')
    op.drop_index(op.f('ix_client_activations_license_id'), table_name='client_activations')
    op.drop_index(op.f('ix_client_activations_id'), table_name='client_activations')
    op.drop_table('client_activations')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_ea_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_admin_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_robot_trades_symbol'), table_name='robot_trades')
    op.drop_index(op.f('ix_robot_trades_id'), table_name='robot_trades')
    op.drop_index(op.f('ix_robot_trades_ea_id'), table_name='robot_trades')
    op.drop_index(op.f('ix_robot_trades_admin_id'), table_name='robot_trades')
    op.drop_table('robot_trades')
    op.drop_index(op.f('ix_master_accounts_id'), table_name='master_accounts')
    op.drop_index(op.f('ix_master_accounts_ea_id'), table_name='master_accounts')
    op.drop_table('master_accounts')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_ea_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_client_email'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_admin_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_activated_device_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_ea_symbols_symbol_name'), table_name='ea_symbols')
    op.drop_index(op.f('ix_ea_symbols_id'), table_name='ea_symbols')
    op.drop_index(op.f('ix_ea_symbols_ea_id'), table_name='ea_symbols')
    op.drop_table('ea_symbols')
    op.drop_index(op.f('ix_copier_trade_events_symbol'), table_name='copier_trade_events')
    op.drop_index(op.f('ix_copier_trade_events_source_admin_id'), table_name='copier_trade_events')
    op.drop_index(op.f('ix_copier_trade_events_master_ticket'), table_name='copier_trade_events')
    op.drop_index(op.f('ix_copier_trade_events_id'), table_name='copier_trade_events')
    op.drop_index(op.f('ix_copier_trade_events_ea_id'), table_name='copier_trade_events')
    op.drop_index(op.f('ix_copier_trade_events_ea_code'), table_name='copier_trade_events')
    op.drop_table('copier_trade_events')
    op.drop_index(op.f('ix_admin_ea_links_target_admin_id'), table_name='admin_ea_links')
    op.drop_index(op.f('ix_admin_ea_links_source_ea_id'), table_name='admin_ea_links')
    op.drop_index(op.f('ix_admin_ea_links_source_ea_code'), table_name='admin_ea_links')
    op.drop_index(op.f('ix_admin_ea_links_source_admin_id'), table_name='admin_ea_links')
    op.drop_index(op.f('ix_admin_ea_links_id'), table_name='admin_ea_links')
    op.drop_table('admin_ea_links')
    op.drop_index(op.f('ix_license_quota_requests_id'), table_name='license_quota_requests')
    op.drop_table('license_quota_requests')
    op.drop_index(op.f('ix_expert_advisors_id'), table_name='expert_advisors')
    op.drop_index(op.f('ix_expert_advisors_ea_code'), table_name='expert_advisors')
    op.drop_index(op.f('ix_expert_advisors_code_name'), table_name='expert_advisors')
    op.drop_index(op.f('ix_expert_advisors_admin_id'), table_name='expert_advisors')
    op.drop_table('expert_advisors')
    op.drop_index(op.f('ix_admin_profiles_id'), table_name='admin_profiles')
    op.drop_index(op.f('ix_admin_profiles_admin_id'), table_name='admin_profiles')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_ticket_maps_symbol'), table_name='ticket_maps')
    op.drop_index(op.f('ix_ticket_maps_master_ticket'), table_name='ticket_maps')
    op.drop_index(op.f('ix_ticket_maps_license_id'), table_name='ticket_maps')
    op.drop_index(op.f('ix_ticket_maps_id'), table_name='ticket_maps')
    op.drop_index(op.f('ix_ticket_maps_execution_id'), table_name='ticket_maps')
    op.drop_index(op.f('ix_ticket_maps_client_ticket'), table_name='ticket_maps')
    op.drop_table('ticket_maps')
    op.drop_index(op.f('ix_live_trades_id'), table_name='live_trades')
    op.drop_table('live_trades')
    op.drop_index(op.f('ix_ai_users_id'), table_name='ai_users')
    op.drop_index(op.f('ix_ai_users_email'), table_name='ai_users')
    op.drop_table('ai_users')
    op.drop_index(op.f('ix_ai_signals_id'), table_name='ai_signals')
    op.drop_table('ai_signals')
    op.drop_index(op.f('ix_ai_settings_id'), table_name='ai_settings')
    op.drop_table('ai_settings')
    op.drop_index(op.f('ix_ai_market_states_id'), table_name='ai_market_states')
    op.drop_table('ai_market_states')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_admin_code'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###