"""initial schema

Revision ID: f0c6e73099b8
Revises: 
Create Date: 2026-04-02 06:31:47.707659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c6e73099b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_code', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_admin_code'), 'admins', ['admin_code'], unique=True)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('admin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('support_email', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_profiles_admin_id'), 'admin_profiles', ['admin_id'], unique=True)
    op.create_index(op.f('ix_admin_profiles_id'), 'admin_profiles', ['id'], unique=False)
    op.create_table('expert_advisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code_name', sa.String(), nullable=False),
    sa.Column('ea_code', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mode_type', sa.String(), nullable=False),
    sa.Column('is_shareable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_advisors_admin_id'), 'expert_advisors', ['admin_id'], unique=False)
    op.create_index(op.f('ix_expert_advisors_code_name'), 'expert_advisors', ['code_name'], unique=False)
    op.create_index(op.f('ix_expert_advisors_ea_code'), 'expert_advisors', ['ea_code'], unique=True)
    op.create_index(op.f('ix_expert_advisors_id'), 'expert_advisors', ['id'], unique=False)
    op.create_table('admin_ea_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_admin_id', sa.Integer(), nullable=False),
    sa.Column('target_admin_id', sa.Integer(), nullable=False),
    sa.Column('source_ea_id', sa.Integer(), nullable=False),
    sa.Column('source_ea_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['source_ea_id'], ['expert_advisors.id'], ),
    sa.ForeignKeyConstraint(['target_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_ea_links_id'), 'admin_ea_links', ['id'], unique=False)
    op.create_index(op.f('ix_admin_ea_links_source_admin_id'), 'admin_ea_links', ['source_admin_id'], unique=False)
    op.create_index(op.f('ix_admin_ea_links_source_ea_code'), 'admin_ea_links', ['source_ea_code'], unique=False)
    op.create_index(op.f('ix_admin_ea_links_source_ea_id'), 'admin_ea_links', ['source_ea_id'], unique=False)
    op.create_index(op.f('ix_admin_ea_links_target_admin_id'), 'admin_ea_links', ['target_admin_id'], unique=False)
    op.create_table('copier_trade_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_admin_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('ea_code', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('master_ticket', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('lot_size', sa.String(), nullable=True),
    sa.Column('sl', sa.String(), nullable=True),
    sa.Column('tp', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.ForeignKeyConstraint(['source_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copier_trade_events_ea_code'), 'copier_trade_events', ['ea_code'], unique=False)
    op.create_index(op.f('ix_copier_trade_events_ea_id'), 'copier_trade_events', ['ea_id'], unique=False)
    op.create_index(op.f('ix_copier_trade_events_id'), 'copier_trade_events', ['id'], unique=False)
    op.create_index(op.f('ix_copier_trade_events_master_ticket'), 'copier_trade_events', ['master_ticket'], unique=False)
    op.create_index(op.f('ix_copier_trade_events_source_admin_id'), 'copier_trade_events', ['source_admin_id'], unique=False)
    op.create_index(op.f('ix_copier_trade_events_symbol'), 'copier_trade_events', ['symbol'], unique=False)
    op.create_table('ea_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ea_symbols_ea_id'), 'ea_symbols', ['ea_id'], unique=False)
    op.create_index(op.f('ix_ea_symbols_id'), 'ea_symbols', ['id'], unique=False)
    op.create_index(op.f('ix_ea_symbols_symbol_name'), 'ea_symbols', ['symbol_name'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('mode_type', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_device_id', sa.String(), nullable=True),
    sa.Column('activated_device_name', sa.String(), nullable=True),
    sa.Column('first_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branding_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_activated_device_id'), 'licenses', ['activated_device_id'], unique=False)
    op.create_index(op.f('ix_licenses_admin_id'), 'licenses', ['admin_id'], unique=False)
    op.create_index(op.f('ix_licenses_client_email'), 'licenses', ['client_email'], unique=False)
    op.create_index(op.f('ix_licenses_ea_id'), 'licenses', ['ea_id'], unique=False)
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True)
    op.create_table('robot_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('lot_size', sa.String(), nullable=True),
    sa.Column('sl', sa.String(), nullable=True),
    sa.Column('tp', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_trades_admin_id'), 'robot_trades', ['admin_id'], unique=False)
    op.create_index(op.f('ix_robot_trades_ea_id'), 'robot_trades', ['ea_id'], unique=False)
    op.create_index(op.f('ix_robot_trades_id'), 'robot_trades', ['id'], unique=False)
    op.create_index(op.f('ix_robot_trades_symbol'), 'robot_trades', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('sl', sa.String(), nullable=True),
    sa.Column('tp', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_admin_id'), 'signals', ['admin_id'], unique=False)
    op.create_index(op.f('ix_signals_ea_id'), 'signals', ['ea_id'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('client_activations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_activations_id'), 'client_activations', ['id'], unique=False)
    op.create_index(op.f('ix_client_activations_license_id'), 'client_activations', ['license_id'], unique=True)
    op.create_table('client_mt5_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('mt_login', sa.String(), nullable=False),
    sa.Column('mt_password', sa.String(), nullable=False),
    sa.Column('mt_server', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.Column('balance', sa.String(), nullable=True),
    sa.Column('equity', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_error', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_mt5_accounts_id'), 'client_mt5_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_client_mt5_accounts_license_id'), 'client_mt5_accounts', ['license_id'], unique=True)
    op.create_index(op.f('ix_client_mt5_accounts_mt_login'), 'client_mt5_accounts', ['mt_login'], unique=False)
    op.create_index(op.f('ix_client_mt5_accounts_mt_server'), 'client_mt5_accounts', ['mt_server'], unique=False)
    op.create_table('client_symbol_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=False),
    sa.Column('trade_direction', sa.String(), nullable=False),
    sa.Column('trades_per_signal', sa.Integer(), nullable=False),
    sa.Column('lot_size', sa.String(), nullable=False),
    sa.Column('max_open_trades', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_symbol_settings_id'), 'client_symbol_settings', ['id'], unique=False)
    op.create_index(op.f('ix_client_symbol_settings_license_id'), 'client_symbol_settings', ['license_id'], unique=False)
    op.create_index(op.f('ix_client_symbol_settings_symbol_name'), 'client_symbol_settings', ['symbol_name'], unique=False)
    op.create_table('trade_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copier_event_id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('master_ticket', sa.String(), nullable=False),
    sa.Column('client_ticket', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('lot_size', sa.String(), nullable=True),
    sa.Column('sl', sa.String(), nullable=True),
    sa.Column('tp', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['copier_event_id'], ['copier_trade_events.id'], ),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_executions_client_ticket'), 'trade_executions', ['client_ticket'], unique=False)
    op.create_index(op.f('ix_trade_executions_copier_event_id'), 'trade_executions', ['copier_event_id'], unique=False)
    op.create_index(op.f('ix_trade_executions_ea_id'), 'trade_executions', ['ea_id'], unique=False)
    op.create_index(op.f('ix_trade_executions_id'), 'trade_executions', ['id'], unique=False)
    op.create_index(op.f('ix_trade_executions_license_id'), 'trade_executions', ['license_id'], unique=False)
    op.create_index(op.f('ix_trade_executions_master_ticket'), 'trade_executions', ['master_ticket'], unique=False)
    op.create_index(op.f('ix_trade_executions_symbol'), 'trade_executions', ['symbol'], unique=False)
    op.create_table('trade_ticket_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('master_ticket', sa.String(), nullable=False),
    sa.Column('child_ticket_index', sa.Integer(), nullable=False),
    sa.Column('client_ticket', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('manually_closed', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_ticket_maps_client_ticket'), 'trade_ticket_maps', ['client_ticket'], unique=False)
    op.create_index(op.f('ix_trade_ticket_maps_ea_id'), 'trade_ticket_maps', ['ea_id'], unique=False)
    op.create_index(op.f('ix_trade_ticket_maps_id'), 'trade_ticket_maps', ['id'], unique=False)
    op.create_index(op.f('ix_trade_ticket_maps_license_id'), 'trade_ticket_maps', ['license_id'], unique=False)
    op.create_index(op.f('ix_trade_ticket_maps_master_ticket'), 'trade_ticket_maps', ['master_ticket'], unique=False)
    op.create_index(op.f('ix_trade_ticket_maps_symbol'), 'trade_ticket_maps', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_ticket_maps_symbol'), table_name='trade_ticket_maps')
    op.drop_index(op.f('ix_trade_ticket_maps_master_ticket'), table_name='trade_ticket_maps')
    op.drop_index(op.f('ix_trade_ticket_maps_license_id'), table_name='trade_ticket_maps')
    op.drop_index(op.f('ix_trade_ticket_maps_id'), table_name='trade_ticket_maps')
    op.drop_index(op.f('ix_trade_ticket_maps_ea_id'), table_name='trade_ticket_maps')
    op.drop_index(op.f('ix_trade_ticket_maps_client_ticket'), table_name='trade_ticket_maps')
    op.drop_table('trade_ticket_maps')
    op.drop_index(op.f('ix_trade_executions_symbol'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_master_ticket'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_license_id'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_id'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_ea_id'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_copier_event_id'), table_name='trade_executions')
    op.drop_index(op.f('ix_trade_executions_client_ticket'), table_name='trade_executions')
    op.drop_table('trade_executions')
    op.drop_index(op.f('ix_client_symbol_settings_symbol_name'), table_name='client_symbol_settings')
    op.drop_index(op.f('ix_client_symbol_settings_license_id'), table_name='client_symbol_settings')
    op.drop_index(op.f('ix_client_symbol_settings_id'), table_name='client_symbol_settings')
    op.drop_table('client_symbol_settings')
    op.drop_index(op.f('ix_client_mt5_accounts_mt_server'), table_name='client_mt5_accounts')
    op.drop_index(op.f('ix_client_mt5_accounts_mt_login'), table_name='client_mt5_accounts')
    op.drop_index(op.f('ix_client_mt5_accounts_license_id'), table_name='client_mt5_accounts')
    op.drop_index(op.f('ix_client_mt5_accounts_id'), table_name='client_mt5_accounts')
    op.drop_table('client_mt5_accounts')
    op.drop_index(op.f('ix_client_activations_license_id'), table_name='client_activations')
    op.drop_index(op.f('ix_client_activations_id'), table_name='client_activations')
    op.drop_table('client_activations')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_ea_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_admin_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_robot_trades_symbol'), table_name='robot_trades')
    op.drop_index(op.f('ix_robot_trades_id'), table_name='robot_trades')
    op.drop_index(op.f('ix_robot_trades_ea_id'), table_name='robot_trades')
    op.drop_index(op.f('ix_robot_trades_admin_id'), table_name='robot_trades')
    op.drop_table('robot_trades')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_ea_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_client_email'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_admin_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_activated_device_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_ea_symbols_symbol_name'), table_name='ea_symbols')
    op.drop_index(op.f('ix_ea_symbols_id'), table_name='ea_symbols')
    op.drop_index(op.f('ix_ea_symbols_ea_id'), table_name='ea_symbols')
    op.drop_table('ea_symbols')
    op.drop_index(op.f('ix_copier_trade_events_symbol'), table_name='copier_trade_events')
    op.drop_index(op.f('ix_copier_trade_events_source_admin_id'), table_name='copier_trade_events')
    op.drop_index(op.f('ix_copier_trade_events_master_ticket'), table_name='copier_trade_events')
    op.drop_index(op.f('ix_copier_trade_events_id'), table_name='copier_trade_events')
    op.drop_index(op.f('ix_copier_trade_events_ea_id'), table_name='copier_trade_events')
    op.drop_index(op.f('ix_copier_trade_events_ea_code'), table_name='copier_trade_events')
    op.drop_table('copier_trade_events')
    op.drop_index(op.f('ix_admin_ea_links_target_admin_id'), table_name='admin_ea_links')
    op.drop_index(op.f('ix_admin_ea_links_source_ea_id'), table_name='admin_ea_links')
    op.drop_index(op.f('ix_admin_ea_links_source_ea_code'), table_name='admin_ea_links')
    op.drop_index(op.f('ix_admin_ea_links_source_admin_id'), table_name='admin_ea_links')
    op.drop_index(op.f('ix_admin_ea_links_id'), table_name='admin_ea_links')
    op.drop_table('admin_ea_links')
    op.drop_index(op.f('ix_expert_advisors_id'), table_name='expert_advisors')
    op.drop_index(op.f('ix_expert_advisors_ea_code'), table_name='expert_advisors')
    op.drop_index(op.f('ix_expert_advisors_code_name'), table_name='expert_advisors')
    op.drop_index(op.f('ix_expert_advisors_admin_id'), table_name='expert_advisors')
    op.drop_table('expert_advisors')
    op.drop_index(op.f('ix_admin_profiles_id'), table_name='admin_profiles')
    op.drop_index(op.f('ix_admin_profiles_admin_id'), table_name='admin_profiles')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_admin_code'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
